version: "3.7"

services:
  application:
    container_name: mediathekviewweb
    image: mediathekview/mediathekviewweb:latest
    restart: always
    depends_on:
      - opensearch
      - valkey
    environment:
      DATA_DIRECTORY: /data
      WEBSERVER_PORT: 8000
      INDEX: true
      WORKER_COUNT:
      WORKER_ARGS:
      VALKEY_HOST: valkey
      VALKEY_PORT:
      VALKEY_PASSWORD:
      VALKEY_DB:
      OPENSEARCH_HOST: opensearch
      OPENSEARCH_PORT: 9200
      MATOMO_ENABLED:
      MATOMO_URL:
      MATOMO_SITE_URL:
      MATOMO_AUTH_TOKEN:
      MATOMO_SITE_ID:
      CONTACT_NAME:
      CONTACT_STREET:
      CONTACT_POSTCODE:
      CONTACT_CITY:
      CONTACT_MAIL:
      INJECT_HTML_PATH:
    volumes:
      - "mediathekviewweb:/data"
    ports:
      - "8000:8000"
    networks:
      - opensearch
      - valkey

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:3
    restart: always
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: MediathekViewWeb01!
    volumes:
      - "opensearch:/usr/share/opensearch/data"
    networks:
      - opensearch

  valkey:
    container_name: valkey
    image: valkey:8-alpine
    restart: always
    command: ["--save", "60", "1", "--loglevel", "info"]
    volumes:
      - "valkey:/data"
    networks:
      - valkey

volumes:
  mediathekviewweb:
  valkey:
  opensearch:

networks:
  opensearch:
  valkey:
