-- indexes a item or updates if already existing
-- index itemID numProperties property value condition [property value condition ...] numTokenProperties tokenProperty numTokens token [token ...] [tokenProperty numTokens token [token ...] ...x]
-- condition can either be LESS, GREATER, EQUAL, NOTEQUAL or NONE
